### PR TITLE
add compatibility with the glam library

### PR DESCRIPTION
**Pull request by gordlea**
This adds some basic compatibility with the glam library.

It implements `FloatPointCompatible<f32>` for `glam::Vec2`, and `FloatPointCompatible<f64>` for `glam::DVec2`, as well as implementing From<> for back and forth between the types.

For IntPoint, it implements From<IVec2> and back.

I tried to follow the conventions used by this project, let me know if you need any changes.

### CODE REVIEW

**Comment by NailxSharipov** [comment]
Hi, gordlea!
Thank you for the contribution! However, I’ve decided not to merge this pull request for two reasons:

- Adding glam as a dependency can cause version conflicts for users relying on a different version.
- I want to keep the library clean and lightweight, allowing users to implement FloatPointCompatible for their types as needed.

I encourage creating a separate crate for glam integration if desired. Thank you for understanding!

**Comment by gordlea** [comment]
That's disappointing. The problem is, to implement a trait, like FloatPointCompatible, you need to either have defined trait or the struct that is implementing the trait in your crate. So basically, if a developer doesn't control either crate, they can't really use the trait. 

Is there another way do this? 

Also, this should work even if you set the glam version to "*", would that change your mind at all?

**Comment by NailxSharipov** [comment]
I see the problem now. Right now I only see an option to write an own wrapper around IntOverlay. Let me think more about it.

**Comment by NailxSharipov** [comment]
After some research I understand that it will be the most simple and comfortable way to add support of external types.
Please accept my apologies.

But let it be a little cleaner in case we need to add some more libraries.

need move all external types to a new module:

src/
|- lib.rs
|- integration/
|- |-mod.rs
|- |-glam.rs


lib.rs:

#[cfg(any(feature = "glam"))]
pub mod integration;


glam.rs:

#[cfg(feature = "glam")]
pub mod glam;


for glam dependencies version it's better to use * as you mentioned

**Comment by gordlea** [comment]
That's great news, I've made the requested changes. Thanks for being open to discussion 👍

**Comment by gordlea** [comment]
I just realized that with this change, since i_overlay re-exports iFloat, we might need to add a glam feature to that which wil activate this one. Once this is merged I can open a PR for that also if you'd like.

**Comment by NailxSharipov** [comment]
And looks like it must be done for both as for iOverlay and as for iTraingle

**Pull request merged**
